apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_be }}
spec:
  ports:
    - port: {{ .Values.exposedport_be }}
      #targetPort: {{ .Values.containerport_be }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service_be }}

